name: Ships
version: 5.0.1.0
main: MoseShipsBukkit.Ships
softdepend:
  - WGCustomFlags
  - WorldGuard
  - Valut
  - Factions
  - WorldBorder
  - Towny
  - GriefPrevention
  - Chairs
commands:
  Ships:
    usage: /ships
    description: all ships commands

